import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./header.css";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["Poppins"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["Poppins"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      <header><h1> Numeric Gwalior</h1></header>
     
      
        {children}

         <footer>
          <h4>All copy rights reserve Numeric</h4>
          </footer>
          
      </body>
    </html>
  );
}
